---
- name: Install SDKMAN!
  shell: curl -s "https://get.sdkman.io" | bash # the script already checks for previous installation

- name: Install JDK and gradle
  # SDKMAN! will manage the JAVA_HOME environment variable after installing java
  # If this is a fresh installation then `yes` command is not needed,
  # but if there has been a default version already, then `yes` command is used to make the latest stable version the default
  shell: "{{ 'bash' if ansible_distribution == 'Ubuntu' else 'zsh' }} -ilc 'yes | sdk install java; yes | sdk install gradle'"
