---
- name: Bootstrap enviroment
  hosts: personal_environment
  connection: local
  pre_tasks:
    - name: Update cache
      become: true
      package:
        update_cache: true
  tasks:
    - name: Package
      tags: package
      import_role:
        name: package

    - name: Node
      tags: node
      import_role:
        name: node

    - name: Font
      tags: font
      import_role:
        name: font

    - name: Neovim
      tags: neovim
      import_role:
        name: neovim

    - name: SDKMAN!
      tags: sdkman
      import_role:
        name: sdkman

    - name: Awesome
      tags: awesome
      import_role:
        name: awesome

    - name: Vifm
      tags: vifm
      import_role:
        name: vifm

    - name: Starship
      tags: starship
      import_role:
        name: starship

    - name: Dotfiles
      tags: dotfiles
      import_role:
        name: dotfiles

    - name: Git
      tags: git
      import_role:
        name: git

    - name: Google style guide
      tags: googlestyleguide
      import_role:
        name: googlestyleguide

    - name: Desktop
      tags: desktop
      import_role:
        name: desktop
