---
- name: Install community.general.dconf module's dependencies
  pip:
    name:
      - psutil>=4.0.0

- name: Show seconds in clock
  community.general.dconf:
    key: '/org/gnome/desktop/interface/clock-show-seconds'
    value: 'true'

- name: Show weekday in clock
  community.general.dconf:
    key: '/org/gnome/desktop/interface/clock-show-weekday'
    value: 'true'

- name: Show battery percentage
  community.general.dconf:
    key: '/org/gnome/desktop/interface/show-battery-percentage'
    value: 'true'

- name: Overly amplify sound
  community.general.dconf:
    key: '/org/gnome/desktop/sound/allow-volume-above-100-percent'
    value: 'true'

- name: Enable night light
  community.general.dconf:
    key: '/org/gnome/settings-daemon/plugins/color/night-light-enabled'
    value: 'true'
