---
- name: Set up desktop for Ubuntu distribution
  include_tasks: '{{ item }}' # https://stackoverflow.com/a/58773661, https://serverfault.com/a/875292
  loop:
    - look_and_feel.linux.yml
    - keybinding.linux.yml
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Set up desktop for MacOSX distribution
  import_tasks: look_and_feel.macosx.yml
  when: ansible_facts['distribution'] == 'MacOSX'
