---
- name: Clone Tmux Plugin Manager repository
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: '{{ ansible_env.HOME }}/.tmux/plugins/tpm'

- name: Set up dotfiles
  import_tasks: unix.yml
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'MacOSX'
