---
- name: Install GNU Stow
  become: true
  package:
    name:
      - stow

- name: Set up dotfiles
  shell:
    chdir: dotfiles
    cmd: stow --target={{ ansible_env.HOME }} --verbose=2 *
  register: stow_result
  changed_when: 'stow_result.stderr is search("LINK: ")'
