---
- name: Install GNU Stow
  become: "{{ false if ansible_facts['distribution'] == 'MacOSX' else true }}"
  package:
    name:
      - stow

- name: Set variables for Ubuntu distribution
  set_fact:
    stow_packages: bash editorconfig ghostty git nvim starship tmux vim
    profile_filename: .profile
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Set variables for MacOSX distribution
  set_fact:
    stow_packages: editorconfig ghostty git nvim starship tmux vim zsh
    profile_filename: .zprofile
  when: ansible_facts['distribution'] == 'MacOSX'

- name: Set up dotfiles
  shell:
    chdir: dotfiles
    cmd: stow --target={{ ansible_facts['env']['HOME'] }} --verbose=2 --restow {{ stow_packages }}
  ignore_errors: true
  register: stow_result
  changed_when: 'stow_result.stderr is search("LINK: ")'

- name: Print GNU Stow messages
  debug:
    msg: '{{ stow_result.stderr_lines }}'

- name: Set up EDITOR environment variable
  lineinfile:
    path: "{{ ansible_facts['env']['HOME'] }}/{{ profile_filename }}"
    regexp: '^export EDITOR='
    line: export EDITOR=nvim

- name: Set up VISUAL environment variable
  lineinfile:
    path: "{{ ansible_facts['env']['HOME'] }}/{{ profile_filename }}"
    regexp: '^export VISUAL='
    line: export VISUAL=nvim
