---
- name: Install GNU Stow
  become: true
  package:
    name:
      - stow

- name: Set up dotfiles
  shell:
    chdir: dotfiles
    cmd: stow --target={{ ansible_env.HOME }} --verbose=2 *
  ignore_errors: true
  register: stow_result
  changed_when: 'stow_result.stderr is search("LINK: ")'

- name: Print GNU Stow messages
  debug:
    msg: '{{ stow_result.stderr_lines }}'

- name: Set up EDITOR environment variable
  lineinfile:
    path: '{{ ansible_env.HOME }}/.profile'
    regexp: '^EDITOR='
    line: EDITOR=nvim

- name: Set up VISUAL environment variable
  lineinfile:
    path: '{{ ansible_env.HOME }}/.profile'
    regexp: '^VISUAL='
    line: VISUAL=nvim
