---
- name: Download pylintrc from Google Python style guide
  get_url:
    url: https://google.github.io/styleguide/pylintrc
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/pylintrc" # refer to the order where Pylint will search for a configuration file: https://pylint.pycqa.org/en/latest/user_guide/usage/run.html#command-line-options
