---
- name: Create font directory
  file:
    path: '{{ font_dir_path }}'
    state: directory

- name: Install font
  shell:
    chdir: '{{ font_dir_path }}'
    cmd: curl -fLO https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/JetBrainsMono/Ligatures/Regular/JetBrainsMonoNerdFont-Regular.ttf
    creates: '{{ font_dir_path }}/JetBrainsMonoNerdFont-Regular.ttf'
