---
- name: Create font directory
  file:
    path: '{{ font_dir_path }}'
    state: directory

- name: Install font
  shell:
    chdir: '{{ font_dir_path }}'
    cmd: curl -fLO https://github.com/ryanoasis/nerd-fonts/raw/HEAD/patched-fonts/Hack/Regular/HackNerdFont-Regular.ttf
    creates: '{{ font_dir_path }}/HackNerdFont-Regular.ttf'
