---
- name: Create font directory
  file:
    path: '{{ font_dir_path }}'
    state: directory

- name: Install font
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/raw/refs/heads/master/patched-fonts/JetBrainsMono/Ligatures/Regular/JetBrainsMonoNerdFont-Regular.ttf
    dest: '{{ font_dir_path }}/JetBrainsMonoNerdFont-Regular.ttf'
