---
- name: Set up global gitignore
  vars:
    gitignore_setup_msg: 'Set up global gitignore as the file:'
    global_gitignore_path: '{{ ansible_env.HOME }}/.gitignore_global'
  shell: |
    CUR_GLOBAL_GITIGNORE_PATH=$(git config --global core.excludesFile)
    if [[ -z $CUR_GLOBAL_GITIGNORE_PATH ]]; then
      git config --global core.excludesFile {{ global_gitignore_path }}
      echo {{ gitignore_setup_msg }} $CUR_GLOBAL_GITIGNORE_PATH
    else
      echo Found previously set global gitignore file: $CUR_GLOBAL_GITIGNORE_PATH
    fi
  register: global_gitignore_setup_message
  args:
    removes: '{{ global_gitignore_path }}'
  changed_when: global_gitignore_setup_message.stdout_lines is search(gitignore_setup_msg)

- name: Print messages
  debug:
    msg: '{{ global_gitignore_setup_message.stdout_lines }}'
