---
- name: Check for global gitignore file
  stat:
    path: '{{ global_gitignore_path }}'
  register: global_gitignore_file

- name: Set up global gitconfig
  community.general.git_config:
    name: core.excludesFile
    add_mode: add
    scope: global
    value: '{{ global_gitignore_path }}'
  when: global_gitignore_file.stat.exists == true

- name: Set git core editor to neovim
  community.general.git_config:
    name: core.editor
    add_mode: add
    scope: global
    value: nvim
