---
- name: Check for global gitignore file
  stat:
    path: '{{ global_gitignore_path }}'
  register: global_gitignore_file

- name: Set up global gitconfig
  community.general.git_config:
    name: core.excludesFile
    add_mode: add
    scope: global
    value: '{{ global_gitignore_path }}'
  when: global_gitignore_file.stat.exists == true

- name: Set git core editor to neovim
  community.general.git_config:
    name: core.editor
    add_mode: add
    scope: global
    value: nvim

- name: Set up git difftool
  community.general.git_config:
    name: diff.tool
    add_mode: add
    scope: global
    value: nvimdiff

- name: Set git difftool to not prompt
  community.general.git_config:
    name: difftool.prompt
    add_mode: add
    scope: global
    value: false

- name: Set up git difftool command
  community.general.git_config:
    name: difftool.nvimdiff.cmd
    add_mode: add
    scope: global
    value: nvim -d "$LOCAL" "$REMOTE"
