---
- name: Install/update starship
  shell: curl -sS https://starship.rs/install.sh | sh -s -- --yes

- name: Set up init script
  lineinfile:
    path: '{{ ansible_env.HOME }}/.bashrc'
    regexp: 'eval "\$\(starship init bash\)"'
    line: eval "$(starship init bash)"
