---
- name: Install essential packages
  become: true
  package:
    name:
      - g++ # contains cc1plus, which is needed by neovim plugin treesitter
      - htop
      - tree
      - tmux
      - vim
      - xsel # tmux plugin's tmux-yank's dependency
