---
- name: Check if there is currently any installation available
  command: nvim -v
  register: nvim_version
  ignore_errors: true
  changed_when: false

- name: Install build prerequisites
  become: true
  package:
    name:
      - ninja-build
      - gettext
      - cmake
      - unzip
      - curl
  when: nvim_version.rc != 0

- name: Install plugins' dependencies
  become: true
  package:
    name:
      - ripgrep # telescope.nvim
  when: nvim_version.rc != 0

- name: Create a directory for storing repositories
  file:
    path: '{{ dep_dir_path }}'
    state: directory
  when: nvim_version.rc != 0

- name: Clone the repository
  git:
    repo: https://github.com/neovim/neovim
    dest: '{{ dep_dir_path }}/neovim'
    version: stable
  when: nvim_version.rc != 0

- name: Build the stable release
  community.general.make:
    chdir: '{{ dep_dir_path }}/neovim'
    jobs: 4
    params:
      CMAKE_BUILD_TYPE: RelWithDebInfo
  when: nvim_version.rc != 0

- name: Install the binary
  become: true
  community.general.make:
    chdir: '{{ dep_dir_path }}/neovim'
    target: install
  when: nvim_version.rc != 0
